<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entidad\**" />
    <Compile Remove="ObjetoValor\**" />
    <Compile Remove="ServicioDominio\**" />
    <EmbeddedResource Remove="Entidad\**" />
    <EmbeddedResource Remove="ObjetoValor\**" />
    <EmbeddedResource Remove="ServicioDominio\**" />
    <None Remove="Entidad\**" />
    <None Remove="ObjetoValor\**" />
    <None Remove="ServicioDominio\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DomainServices\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.14.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

</Project>

